input_path: data/input/sample_mail.json
output_path: data/output/result.json
db_path: db/records.db
summary:
  model: heack/HeackMT5-ZhSum100k
  use_gpu: false

classify:
  model: morit/chinese_xlm_xnli
  labels:
    - 請求技術支援
    - 申請修改資訊
    - 詢問流程或規則
    - 投訴與抱怨
    - 業務接洽或報價
    - 其他
